### ISSUE TITLE
Rounded Corners & Image Border

### ISSUE THREAD

**Issue by wvujeb** [thiagosf/SkitterSlideshow#10]
I was trying to modify skitter.styles.css to add rounded corners to the slide show. If you add a border radius to .box_skitter .image img, the border works on the first image and then the corners are square again. The corners round again just before switching to the next image. Is there a way to apply the border radius to the images?

Also, I get a border on my images in IE that shows because of the link. I cannot figure out how to get rid of it.

Thanks.

**Comment by lostgdi** [comment]
thanks val-litvak .
