### ISSUE TITLE
Show that there is a problem

### ISSUE THREAD

**Issue by geekmakersun** [thiagosf/SkitterSlideshow#49]
I have a problem，The display is out of place
![image](https://user-images.githubusercontent.com/20056211/125592507-44faca1a-c9db-485a-a496-059386f49103.png)

This is a demo：https://4a8aae90.webpack4-x.pages.dev/

**Comment by thiagosf** [comment]
Hi! It happens because your images css has `max-width: 100%`, to fix it, create a css hotfix like that:

```css
.skitter img { max-width: initial; }
```

**Comment by geekmakersun** [comment]
Thank you, but I encountered a new problem
![image](https://user-images.githubusercontent.com/20056211/125641968-4a473cf9-c742-4838-b469-aa11df687bbb.png)
a demo https://webpack4-x.pages.dev/#

github url: https://github.com/GeekMakerSun/webpack4.x/tree/3f45dbff06a937e2ac3edf10388b97b7f51139a4
https://github.com/GeekMakerSun/webpack4.x/blob/3f45dbff06a937e2ac3edf10388b97b7f51139a4/src/pages/index/index.html

**Comment by GeekMakerSun** [comment]
I seem to have solved it
I use `  .skitter {
    width: 100vw;
    max-width: initial;
  }`

**Comment by GeekMakerSun** [comment]
a demo : https://d15a39bb.webpack4-x.pages.dev/

**Comment by geekmakersun** [comment]
I seem to have solved it  https://c7ad4fa4.webpack4-x.pages.dev/  I use    `.skitter {
    width: 100vw !important;
    max-width: initial;
  }
`
  `.skitter img {
    max-width: initial;
    width: 100vw !important;
  }`

**Comment by geekmakersun** [comment]
https://webpack4-x.pages.dev/

**Comment by thiagosf** [comment]
Cool!
